import { useState, useEffect } from "react";
import { motion } from "motion/react";
import { FileText, Download, Wand2, ArrowRight, Pencil, Check, PenTool } from "lucide-react";
import LoadingDonut from "../ui/LoadingDonut";
import StepHeader from "../ui/StepHeader";
import Notice from "../ui/Notice";
import { saveAs } from "file-saver";
import { cn } from "../../lib/utils";
import { exportScript, generateScript, isRateLimitError, summarizeScript, type ExportFormat } from "../../services/api";

interface Step3Props {
  niche: string;
  topic: string;
  style: string;
  duration: string;
  onNext: (script: string, summary: string) => void;
  initialScript?: string;
  key?: string;
}

export default function Step3_Script({ niche, topic, style, duration, onNext, initialScript }: Step3Props) {
  const [script, setScript] = useState(initialScript || "");
  const [summary, setSummary] = useState("");
  const [isGenerating, setIsGenerating] = useState(!initialScript);
  const [isEditing, setIsEditing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!initialScript) {
      handleGenerate();
    }
  }, [topic]);

  // Script + summary are generated by the backend (core/services/scripts.py).
  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      // 1. Generate Script
      const fullScript = await generateScript({ topic, niche, duration, style });
      setScript(fullScript);

      // 2. Generate Summary
      setSummary(await summarizeScript(fullScript));
    } catch (e) {
      console.error("Script Gen Error:", e);
      if (isRateLimitError(e)) {
        setError("AI Quota limit reached. Please wait a moment and try again.");
      } else {
        setError("Narrative generation failed. Check your connection.");
      }
    } finally {
      setIsGenerating(false);
    }
  };

  // Files are built by the backend (core/services/export.py) and saved in the browser.
  const downloadScript = async (format: ExportFormat) => {
    try {
      const blob = await exportScript(topic, script, format);
      saveAs(blob, `${topic.slice(0, 20)}.${format}`);
    } catch (e) {
      console.error("Export Error:", e);
      setError("Export failed. Please try again.");
    }
  };

  const exportTxt = () => downloadScript("txt");
  const exportDocx = () => downloadScript("docx");

  if (isGenerating) {
    return (
      <div className="flex items-center justify-center py-24">
        <LoadingDonut label="Writing your script..." />
      </div>
    );
  }

  const wordCount = script.trim() ? script.trim().split(/\s+/).length : 0;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-5xl mx-auto"
    >
      <StepHeader
        icon={<PenTool />}
        eyebrow="Step 3 · Script"
        title={topic}
      />
      <div className="flex flex-wrap justify-center gap-2 -mt-6 mb-8">
        <span className="chip">{niche}</span>
        <span className="chip">{duration}</span>
        <span className="chip">{style}</span>
      </div>

      {error && <Notice className="mb-6" onDismiss={() => setError(null)}>{error}</Notice>}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Script editor */}
        <div className="lg:col-span-2 surface flex flex-col h-[560px] overflow-hidden">
          <div className="flex items-center justify-between gap-3 px-5 py-3 border-b border-zinc-100">
            <div className="flex items-center gap-2 text-sm font-semibold text-zinc-700">
              <span className="w-2 h-2 bg-emerald-500 rounded-full" />
              Script
              <span className="text-xs font-normal text-zinc-400">· {wordCount} words</span>
            </div>
            <div className="flex items-center gap-1.5">
              <button onClick={exportTxt} className="btn-ghost btn-sm" title="Download as .txt">
                <FileText className="w-3.5 h-3.5" /> TXT
              </button>
              <button onClick={exportDocx} className="btn-ghost btn-sm" title="Download as .docx">
                <Download className="w-3.5 h-3.5" /> DOCX
              </button>
              <button
                onClick={() => setIsEditing(!isEditing)}
                className={cn("btn-sm", isEditing ? "btn-primary" : "btn-ghost")}
              >
                {isEditing ? <Check className="w-3.5 h-3.5" /> : <Pencil className="w-3.5 h-3.5" />}
                <span>{isEditing ? "Done" : "Edit"}</span>
              </button>
            </div>
          </div>
          <div className="flex-grow overflow-y-auto p-6 text-[15px] leading-relaxed text-zinc-700 whitespace-pre-wrap">
            {isEditing ? (
              <textarea
                className="w-full h-full p-4 bg-zinc-50 rounded-xl border border-zinc-200 focus:border-brand-primary focus:ring-4 focus:ring-brand-primary/10 outline-none leading-relaxed resize-none text-zinc-800"
                value={script}
                onChange={(e) => setScript(e.target.value)}
                autoFocus
              />
            ) : (
              <div className="space-y-4">
                {script.split("\n").filter(p => p.trim()).map((para, i) => (
                  <p key={i}>{para.replace(/[#*]/g, '')}</p>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Summary + continue */}
        <div className="flex flex-col gap-4">
          <div className="card-vibrant flex flex-col max-h-[460px]">
            <h3 className="font-salena text-sm font-semibold flex items-center gap-2 mb-3 !text-white">
              <Wand2 className="w-4 h-4" />
              Summary
            </h3>
            <div className="text-white/90 text-sm leading-relaxed overflow-y-auto pr-1">
              {summary || "Summarising your script..."}
            </div>
          </div>

          <button onClick={() => onNext(script, summary)} className="btn-primary btn-lg w-full mt-auto">
            <span>Continue to audio</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </motion.div>
  );
}
